language: en

pipeline:
  - name: "WhitespaceTokenizer"
    "intent_tokenization_flag": False
    "intent_split_symbol": "_"
    "token_pattern": None
  - name: LanguageModelFeaturizer
    model_name: "bert"
    model_weights: "rasa/LaBSE"
    cache_dir: null
  - name: "DucklingEntityExtractor"
    url: "http://localhost:8000"
    dimensions: ["time", "phone-number", "date"]
  - name: DIETClassifier
    epochs: 77
  - name: ResponseSelector
    epochs: 50
    retrieval_intent: faq

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: RulePolicy
    core_fallback_threshold: 0.35
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: True
